### ISSUE TITLE
How to get forge working?

### ISSUE THREAD

**Issue by RobertWielewicki** [sammko/picomc#16]
I got forge 1.12.2 from correct windows installer and when i replace both 1.12.2.jar and 1.12.2.json it doesnt work. The 1.12.2.json is being replaced. Is there a way to modify json or something to get it to work? On other note i got 1.18 development preview working by replacing 1.17 files with 1.18.

**Comment by RobertWielewicki** [comment]
And I mean forge as plain forge (for any version prefferably) because I would want  to do some custom modding rather than curse mods browsing

**Comment by RobertWielewicki** [comment]
Ok I got this to work by
picomc mod loader forge install 14.23.5.2855
picomc instance config V_1.12.2 set version 1.12.2-forge-14.23.5.2855
The program is very good, but I would love to help with some documentation.
Also, Can I list all available forge versions/install manually downloaded one?

**Comment by RobertWielewicki** [comment]
Ok, so whilst trying to get forge for 1.16.5 working version at least 36.2.0 (prefferably 36.2.4)
Older version work (36.1.35), newer crashes java.
`
INFO Launching instance: a
INFO Using version: 1.16.5-forge-36.2.0
INFO Using account: TEST123
INFO Using java version: 11.0.12 (OpenJDK 64-Bit Server VM)
WARNING The version of Minecraft you are launching uses java 1.8.0 by default.
WARNING You may experience issues, especially with older versions of Minecraft.
INFO Checking libraries.
INFO Checking 2592 assets.
INFO Launching the game
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.cavoj.picoforgewrapper.Main.main(Main.java:34)
Caused by: java.lang.NoSuchMethodError: 'net.minecraftforge.installer.json.Install net.minecraftforge.installer.json.Util.loadInstallProfile()'
	at net.cavoj.picoforgewrapper.Installer.ensure(Installer.java:37)
	... 5 more
`
The reason is not java11, java8 throws identical error.
`INFO Launching instance: a
INFO Using version: 1.16.5-forge-36.2.0
INFO Using account: TEST123
INFO Using java version: 1.8.0_292 (OpenJDK 64-Bit Server VM)
INFO Checking libraries.
INFO Checking 2592 assets.
INFO Launching the game
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.cavoj.picoforgewrapper.Main.main(Main.java:34)
Caused by: java.lang.NoSuchMethodError: net.minecraftforge.installer.json.Util.loadInstallProfile()Lnet/minecraftforge/installer/json/Install;
	at net.cavoj.picoforgewrapper.Installer.ensure(Installer.java:37)
	... 5 more
`

**Comment by RobertWielewicki** [comment]
```
#picomc mod loader forge version 36.2.4
INFO Fetching Forge metadata
INFO Resolving version
INFO Found Forge version 36.2.4 for Minecraft 1.16.5
```
```
#ls
1.16.5-forge-36.2.4.json
```

**Comment by sammko** [comment]
Hmm yes, this is bad news. The forge installer has changed, this will need fixing in https://github.com/sammko/PicoForgeWrapper. I will take a look at it, I hope sometime this week, but I can't promise that.

Probably the easiest way to get it running right now is to run the forge installer manually and point it at the picomc install folder, which hopefully should work (not certain though)

**Comment by sammko** [comment]
So this has been more complicated than expected, but I recently got time to look at it and got a prototype working. Release with working forge should be coming in the near future.

**Comment by sammko** [comment]
This should be fixed now, please reopen if that is not the case
