### ISSUE TITLE
Picomc error during launch - missing positional arguments

### ISSUE THREAD

**Issue by Zajozor** [sammko/picomc#2]
Platform: MacOS
```
(base) ➜  ~ java -version
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)
(base) ➜  ~ python -V
Python 3.7.2
```
The python is from anaconda.

Installed using `pip install picomc`
```
(base) ➜  ~ which pip
/usr/local/anaconda3/bin/pip
(base) ➜  ~ which picomc
/usr/local/anaconda3/bin/picomc
(base) ➜  ~ picomc config show
[default] java.path: java
[default] java.memory.min: 512M
[default] java.memory.max: 2G
[default] java.jvmargs: -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

```

Trying to launch anything results in various errors:

```
(base) ➜  ~ picomc --debug play
DEBUG picomc, version 0.4.0
DEBUG Python 3.7.2
DEBUG Resolving default application root
DEBUG Using application directory: /Users/zajozor/Library/Application Support/picomc
DEBUG Loading Config from /Users/zajozor/Library/Application Support/picomc/accounts.json
DEBUG Commiting all dirty configs
Traceback (most recent call last):
  File "/usr/local/anaconda3/bin/picomc", line 8, in <module>
    sys.exit(main())
  File "/usr/local/anaconda3/lib/python3.7/site-packages/picomc/main.py", line 8, in main
    picomc_cli(obj=es)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/anaconda3/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/picomc/cli/utils.py", line 16, in wrapper
    fn(x, *a, **kwa)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/picomc/cli/utils.py", line 16, in wrapper
    fn(x, *a, **kwa)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
TypeError: play() missing 2 required positional arguments: 'am' and 'im'
```

and

```
(base) ➜  ~ picomc instance list
t
(base) ➜  ~ picomc --debug instance launch t
DEBUG picomc, version 0.4.0
DEBUG Python 3.7.2
DEBUG Resolving default application root
DEBUG Using application directory: /Users/zajozor/Library/Application Support/picomc
DEBUG Loading Config from /Users/zajozor/Library/Application Support/picomc/accounts.json
DEBUG Commiting all dirty configs
Traceback (most recent call last):
  File "/usr/local/anaconda3/bin/picomc", line 8, in <module>
    sys.exit(main())
  File "/usr/local/anaconda3/lib/python3.7/site-packages/picomc/main.py", line 8, in main
    picomc_cli(obj=es)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/anaconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/anaconda3/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/picomc/cli/instance.py", line 15, in inner
    return fn(*args, instance_name=sanitize_name(instance_name), **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/picomc/cli/utils.py", line 16, in wrapper
    fn(x, *a, **kwa)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/picomc/cli/utils.py", line 16, in wrapper
    fn(x, *a, **kwa)
TypeError: launch() missing 1 required positional argument: 'im'
```

Let me know what am I doing wrong or what else can I provide!

**Comment by Zajozor** [comment]
Upgrading `click` seems to help with this:

```
(base) ➜  ~ pip list |grep click
click                              6.7
WARNING: You are using pip version 20.1.1; however, version 20.2.1 is available.
You should consider upgrading via the '/usr/local/anaconda3/bin/python3 -m pip install --upgrade pip' command.
(base) ➜  ~ pip install --upgrade click
Collecting click
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
     |████████████████████████████████| 82 kB 625 kB/s
Installing collected packages: click
  Attempting uninstall: click
    Found existing installation: click 6.7
    Uninstalling click-6.7:
      Successfully uninstalled click-6.7
Successfully installed click-7.1.2
WARNING: You are using pip version 20.1.1; however, version 20.2.1 is available.
You should consider upgrading via the '/usr/local/anaconda3/bin/python3 -m pip install --upgrade pip' command.
(base) ➜  ~ picomc play
Choose your account name:
>
```

**Comment by sammko** [comment]
Yes, that's the correct solution. Click 7 is a hard requirement. See abc5314

**Comment by Zajozor** [comment]
Thanks for the fix.
Would you mind updating the pypi version as well, so that it is easier to explain to some friends?
