### ISSUE TITLE
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

### ISSUE THREAD

**Issue by somePythonProgrammer** [sammko/picomc#25]
## PICOMC PLAY does not work.

Java --version output:

    java 17.0.1 2021-10-19 LTS
    Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
    Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)

logs:

    Traceback (most recent call last):
    File "c:\users\__\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "c:\users\__\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "C:\Users\__\AppData\Local\Programs\Python\Python38\Scripts\picomc.exe\__main__.py", line 7, in <module>
    File "c:\users\__\appdata\local\programs\python\python38\lib\site-packages\picomc\__init__.py", line 18, in main
      picomc_cli()
    File "c:\users\__\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 829, in __call__
      return self.main(*args, **kwargs)
    File "c:\users\__\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 782, in main
      rv = self.invoke(ctx)
    File "c:\users\__\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1259, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "c:\users\__\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1066, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "c:\users\__\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 610, in invoke
      return callback(*args, **kwargs)
    File "c:\users\__\appdata\local\programs\python\python38\lib\site-packages\click\decorators.py", line 73, in new_func
      return ctx.invoke(f, obj, *args, **kwargs)
    File "c:\users\__\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 610, in invoke
      return callback(*args, **kwargs)
    File "c:\users\__\appdata\local\programs\python\python38\lib\site-packages\picomc\cli\utils.py", line 16, in wrapper
      fn(x, *a, **kwa)
    File "c:\users\__\appdata\local\programs\python\python38\lib\site-packages\click\decorators.py", line 73, in new_func
      return ctx.invoke(f, obj, *args, **kwargs)
    File "c:\users\__\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 610, in invoke
      return callback(*args, **kwargs)
    File "c:\users\__\appdata\local\programs\python\python38\lib\site-packages\picomc\cli\utils.py", line 16, in wrapper
      fn(x, *a, **kwa)
    File "c:\users\__\appdata\local\programs\python\python38\lib\site-packages\click\decorators.py", line 73, in new_func
      return ctx.invoke(f, obj, *args, **kwargs)
    File "c:\users\__\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 610, in invoke
      return callback(*args, **kwargs)
    File "c:\users\__\appdata\local\programs\python\python38\lib\site-packages\picomc\cli\play.py", line 40, in play
      inst.launch(account, version, verify_hashes=verify)
    File "c:\users\__\appdata\local\programs\python\python38\lib\site-packages\picomc\instance.py", line 127, in launch
      java_info = assert_java(java, vobj.java_version)
    File "c:\users\__\appdata\local\programs\python\python38\lib\site-packages\picomc\java\javainfo.py", line 84, in assert_java
      jinfo = get_java_info(java)
    File "c:\users\__\appdata\local\programs\python\python38\lib\site-packages\picomc\java\javainfo.py", line 40, in get_java_info
      props = ElementTree.fromstring(xmlstr)
    File "c:\users\__\appdata\local\programs\python\python38\lib\xml\etree\ElementTree.py", line 1321, in XML
      return parser.close()
  xml.etree.ElementTree.ParseError: no element found: line 1, column 0

**Comment by sammko** [comment]
Interesting, can you please try running
`java -cp "c:\users\__\appdata\local\programs\python\python38\lib\site-packages\picomc\java" SysDump`

**Comment by somePythonProgrammer** [comment]
It gives me this:

    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
    <properties>
    <entry key="java.specification.version">17</entry>
    <entry key="sun.cpu.isalist">amd64</entry>
    <entry key="sun.jnu.encoding">Cp1252</entry>
    <entry key="java.class.path">c:\users\__\appdata\local\programs\python\python38\lib\site-packages\picomc\java</entry>
    <entry key="java.vm.vendor">Oracle Corporation</entry>
    <entry key="sun.arch.data.model">64</entry>
    <entry key="user.variant"></entry>
    <entry key="java.vendor.url">https://java.oracle.com/</entry>
    <entry key="java.vm.specification.version">17</entry>
    <entry key="os.name">Windows 10</entry>
    <entry key="sun.java.launcher">SUN_STANDARD</entry>
    <entry key="user.country">IN</entry>
    <entry key="sun.boot.library.path">C:\Program Files\Java\jdk-17.0.1\bin</entry>
    <entry key="sun.java.command">SysDump</entry>
    <entry key="jdk.debug">release</entry>
    <entry key="sun.cpu.endian">little</entry>
    <entry key="user.home">C:\Users\__</entry>
    <entry key="user.language">en</entry>
    <entry key="sun.stderr.encoding">cp437</entry>
    <entry key="java.specification.vendor">Oracle Corporation</entry>
    <entry key="java.version.date">2021-10-19</entry>
    <entry key="java.home">C:\Program Files\Java\jdk-17.0.1</entry>
    <entry key="file.separator">\</entry>
    <entry key="java.vm.compressedOopsMode">32-bit</entry>
    <entry key="line.separator">
    </entry>
    <entry key="sun.stdout.encoding">cp437</entry>
    <entry key="java.vm.specification.vendor">Oracle Corporation</entry>
    <entry key="java.specification.name">Java Platform API Specification</entry>
    <entry key="user.script"></entry>
    <entry key="sun.management.compiler">HotSpot 64-Bit Tiered Compilers</entry>
    <entry key="java.runtime.version">17.0.1+12-LTS-39</entry>
    <entry key="user.name">__</entry>
    <entry key="path.separator">;</entry>
    <entry key="os.version">10.0</entry>
    <entry key="java.runtime.name">Java(TM) SE Runtime Environment</entry>
    <entry key="file.encoding">Cp1252</entry>
    <entry key="java.vm.name">Java HotSpot(TM) 64-Bit Server VM</entry>
    <entry key="java.vendor.url.bug">https://bugreport.java.com/bugreport/</entry>
    <entry key="java.io.tmpdir">C:\Users\__\AppData\Local\Temp\</entry>
    <entry key="java.version">17.0.1</entry>
    <entry key="user.dir">C:\Users\__</entry>
    <entry key="os.arch">amd64</entry>
    <entry key="java.vm.specification.name">Java Virtual Machine Specification</entry>
    <entry key="sun.os.patch.level"></entry>
    <entry key="native.encoding">Cp1252</entry>
    <entry key="java.library.path">C:\Program Files\Java\jdk-17.0.1\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.5\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.5\libnvvp;C:\Python310\Scripts\;C:\Python310\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\Program Files\NVIDIA Corporation\Nsight Compute 2021.3.1\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\dotnet\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Git\cmd;C:\Users\__\AppData\Local\Programs\Python\Python38\;C:\Users\__\AppData\Local\Programs\Python\Python38\Scripts\;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.5\bin\\..\extras\CUPTI\lib64;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Users\__\AppData\Local\Programs\Python\Python310\;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.5\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.5\libnvvp;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\ProgramData\chocolatey\bin;C:\Users\__\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Program Files\NVIDIA Corporation\Nsight Compute 2021.3.1\;C:\src\flutter\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\dotnet\;C:\Program Files\jdk-17.0.2\bin;C:\Program Files\Docker\Docker\resources\bin;C:\Program Files\Android\Android Studio\jre\bin;C:\Program Files\Java\jdk-17.0.1\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Android\Android Studio\bin;C:\Users\__\AppData\Local\Android\Sdk\tools;C:\Users\__\AppData\Local\Android\Sdk\cmdline-tools;C;C:\Users\__\AppData\Local\Programs\Microsoft VS Code;C:\Users\__\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\__\AppData\Local\Programs\Python\Python310\Scripts\;;.</entry>
    <entry key="java.vm.info">mixed mode, sharing</entry>
    <entry key="java.vendor">Oracle Corporation</entry>
    <entry key="java.vm.version">17.0.1+12-LTS-39</entry>
    <entry key="sun.io.unicode.encoding">UnicodeLittle</entry>
    <entry key="java.class.version">61.0</entry>
    </properties>

**Comment by sammko** [comment]
Alright, so it seems `picomc` is either trying to use a different java than the one in your `PATH` (although the versions are the same, so that is suspicious), or something else is badly broken. Have you changed any configuration? If not, try running `picomc --debug play` and look for the following in the output: `Detected JAVA_HOME, using as default`. Then look at your system environment variables and see if you have a `JAVA_HOME` and if the value makes sense.

**Comment by somePythonProgrammer** [comment]
Wierd... I just tried it today and it worked... It wasn't working till yesterday!
Also I can't see `Detected JAVA_HOME, using as default` in the debug, but it still worked!

**Comment by sammko** [comment]
Yeah, `JAVA_HOME` is not required, if it's unset simply `java` is used which is looked up in the `PATH`. Who knows what was wrong, though. Glad it works now.
