### ISSUE TITLE
Error when installing forge

### ISSUE THREAD

**Issue by nixietab** [sammko/picomc#37]
trying to install any version of forge with picomc returns a java error

```
INFO Launching instance: default
INFO Using version: 1.19.4-forge-45.2.0
INFO Using account: Nixietab
INFO Using java version: 21.0.2 (OpenJDK 64-Bit Server VM)
WARNING The version of Minecraft you are launching uses java 17 by default.
WARNING You may experience issues, especially with older versions of Minecraft.
INFO Checking libraries.
INFO Checking 3545 assets.
INFO Launching the game
PicoForgeWrapper: Missing artifact: client-1.19.4-20230314.122934-srg.jar
PicoForgeWrapper: Missing artifact: client-1.19.4-20230314.122934-slim.jar
PicoForgeWrapper: Missing artifact: client-1.19.4-20230314.122934-extra.jar
PicoForgeWrapper: Some artifacts were missing, running Forge installer
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at net.cavoj.picoforgewrapper.Main.main(Main.java:33)
Caused by: java.lang.NoSuchMethodError: 'boolean net.minecraftforge.installer.actions.PostProcessors.process(java.io.File, java.io.File, java.io.File, java.io.File)'
        at net.cavoj.picoforgewrapper.PicoClientInstall.runPico(PicoClientInstall.java:15)
        at net.cavoj.picoforgewrapper.Installer.ensure(Installer.java:49)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 2 more
```

**Comment by nixietab** [comment]
is it posible to merge it so it can be used without editing the code?

**Comment by sammko** [comment]
It is possible and I will do it eventually.

**Comment by sammko** [comment]
Should be done now. You will probably need to delete the version manifest that you have already generated and re-create it, for it to contain the new wrapper dependency.
